services:
  - type: web
    name: alfadata
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn alfadata_project.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: alfadata_project.settings
      - key: PYTHON_VERSION
        value: 3.11.8
